---
title: ""  
author: "`r rworkflows::use_badges()`" 
date: "<h4>README updated: <i>`r format( Sys.Date(), '%b-%d-%Y')`</i></h4>"
output:
  github_document
---

<!-- To modify Package/Title/Description/Authors fields, edit the DESCRIPTION file -->

```{r, echo=FALSE, include=FALSE}
pkg <- read.dcf("DESCRIPTION", fields = "Package")[1]
title <- read.dcf("DESCRIPTION", fields = "Title")[1]
description <- read.dcf("DESCRIPTION", fields = "Description")[1]
URL <- read.dcf('DESCRIPTION', fields = 'URL')[1]
owner <- strsplit(URL,"/")[[1]][4]
repo <- strsplit(URL,"/")[[1]][5]
```

## ``r pkg``: `r gsub("\n","",title)`

### `r gsub("\n","",description)`

## Installation 

```R
if(!require("remotes")) install.packages("remotes")

remotes::install_github("`r paste(owner,repo,sep='/')`")
library(`r pkg`)
```
## Documentation 

### [Website](https://`r owner`.github.io/`r repo`) 
### [Getting started](https://`r owner`.github.io/`r repo`/articles/`r pkg`) 

<hr>

## Contact
 
### [Neurogenomics Lab](https://www.neurogenomics.co.uk/)

UK Dementia Research Institute  
Department of Brain Sciences  
Faculty of Medicine  
Imperial College London   
[GitHub](https://github.com/neurogenomics)  
[DockerHub](https://hub.docker.com/orgs/neurogenomicslab)  

<br>

## Session Info

<details>
```{r}
utils::sessionInfo()
```
</details>

